### ISSUE TITLE
problem 1  translated to Arabic

### ISSUE THREAD

**Issue by m-agh-ze** [CodeAbbey/Translations#28]
https://gist.github.com/m-agh-ze/35144bb2135ddc0cb2f5

problem 1 translated to Arabic

**Comment by RodionGork** [comment]
Wow! That's great, though I need a small time to find out how can we add "right-to-left" text rendering, if it is possible... I'll try to solve all technical issues soon and will merge this!

**Comment by m-agh-ze** [comment]
Sounds great....
I'll keep translating when ever i find my self free .
and good luck in solving the text rendering problem.

**Comment by RodionGork** [comment]
Thanks a lot, it is merged! Hope text rendering works properly :)
