### ISSUE TITLE
Problem 41 median of 3 translated into SK lang.

### ISSUE THREAD

**Issue by JarRajko** [CodeAbbey/Translations#73]
https://gist.github.com/JarRajko/b0c12ec6acf28fa60c341c3133621146.js

//Note: I will proboably do more of these as it's something easy to start with before 
//preparing to school or completing some duties  or generally something
//meaningful. 

- Sincerely Radovan M.

**Comment by RodionGork** [comment]
Done! thanks and sorry for delay!

This "js" url confused me somewhat at first :)
