### ISSUE TITLE
Problem 213 - micro life translated into SK lang.

### ISSUE THREAD

**Issue by JarRajko** [CodeAbbey/Translations#78]
https://gist.github.com/JarRajko/1ce29bf40673fee617bb58b68c8d22dd

I translated this so others can take a look at the most difficult task.
(Let's pressume that this is the most difficult one)

**Comment by RodionGork** [comment]
Ha-ha, that's cool!

I don't know, whether "the most difficult", because it is a challenge and here are different ways. I know that for me here were more difficult ones (usually with some whimsical algorithm) - but surely it depends on which tasks the person has got used to.

Thanks a lot!
