### ISSUE TITLE
Task 16 translated into sk lang.

### ISSUE THREAD

**Issue by JarRajko** [CodeAbbey/Translations#79]
https://gist.github.com/JarRajko/54e403c55cbeecd021058f0cedcb24fc

//I am not really sure about formatting here something was moved a little bit
//as a result of longer words being used

**Comment by RodionGork** [comment]
Seems to be less or more ok :) I usually can do some formatting improvements when copying to repo. And anyway anything could be improved later, perhaps by other people, by pull-requests etc...

Thank you very much! sorry for it took me so long to look into translations you sent.
